### ISSUE TITLE
Uncaught Error: target of repeat operator is not specified

### ISSUE THREAD

**Issue by ajwsert** [azizur/atom-wordpress-api#16]
[Enter steps to reproduce below:]

1. Open a Wordpress php file.
2. Change the syntax to WordPress.

**Atom Version**: 1.12.5
**Electron Version**: 1.3.9
**System**: Windows 7
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: target of repeat operator is not specified

```
At D:\PortableApps\Atom\resources\app.asar\node_modules\first-mate\lib\scanner.js:31

Error: target of repeat operator is not specified
    at Error (native)
    at Scanner.module.exports.Scanner.createScanner (D:\PortableApps\Atom\resources\app.asar\node_modules\first-mate\lib\scanner.js:31:24)
    at Scanner.module.exports.Scanner.getScanner (D:\PortableApps\Atom\resources\app.asar\node_modules\first-mate\lib\scanner.js:37:31)
    at Scanner.module.exports.Scanner.findNextMatch (D:\PortableApps\Atom\resources\app.asar\node_modules\first-mate\lib\scanner.js:56:22)
    at Rule.module.exports.Rule.findNextMatch (D:\PortableApps\Atom\resources\app.asar\node_modules\first-mate\lib\rule.js:99:28)
    at Rule.module.exports.Rule.getNextTags (D:\PortableApps\Atom\resources\app.asar\node_modules\first-mate\lib\rule.js:141:21)
    at Grammar.module.exports.Grammar.tokenizeLine (D:\PortableApps\Atom\resources\app.asar\node_modules\first-mate\lib\grammar.js:150:44)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (D:\PortableApps\Atom\resources\app.asar\src\tokenized-buffer.js:407:27)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (D:\PortableApps\Atom\resources\app.asar\src\tokenized-buffer.js:395:19)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (D:\PortableApps\Atom\resources\app.asar\src\tokenized-buffer.js:205:43)
    at D:\PortableApps\Atom\resources\app.asar\src\tokenized-buffer.js:182:26
    at D:\PortableApps\Atom\resources\app.asar\node_modules\underscore\underscore.js:666:47
```

### Commands

```
     -8:27.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -8:20.8.0 grammar-selector:show (atom-text-editor.editor)
     -8:19 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:06.8.0 grammar-selector:show (atom-text-editor.editor)
     -8:05.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:04.1.0 grammar-selector:show (atom-text-editor.editor)
  2x -8:02.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -5:06.3.0 atom-wpcodex:lookup (atom-text-editor.editor.is-focused)
     -3:52 grammar-selector:show (atom-text-editor.editor)
     -3:49.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:17 grammar-selector:show (atom-text-editor.editor)
     -0:14.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.6.0 grammar-selector:show (atom-text-editor.editor)
     -0:11 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.9.0 grammar-selector:show (atom-text-editor.editor)
     -0:08.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "disabledPackages": [
      "markdown-pdf",
      "markdown-themeable-pdf",
      "linter-raml",
      "api-workbench",
      "atom-commander",
      "atom-html-preview",
      "autohide-tree-view",
      "tool-bar-main",
      "tool-bar-shortcuts",
      "tool-bar-atom",
      "browser-plus",
      "linter-spell"
    ],
    "packagesWithKeymapsDisabled": [],
    "projectHome": "D:\\PortableApps\\Atom\\github",
    "telemetryConsent": "no",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
api-docs, v0.0.6 (active)
api-workbench, v0.8.46 (inactive)
atom-beautify, v0.30.4 (active)
atom-commander, v0.9.0 (inactive)
atom-easy-jsdoc, v4.12.1 (inactive)
atom-html-preview, v0.1.22 (inactive)
atom-sql-list, v0.3.1 (inactive)
atom-unsaved-changes, v0.4.0 (inactive)
atom-wpcodex, v1.1.0 (active)
autoclose-html, v0.23.0 (active)
autocomplete-html-entities, v0.1.0 (active)
autocomplete-wordpress-hooks, v0.2.2 (active)
autocomplete-xml, v0.9.4 (active)
autohide-tree-view, v0.25.1 (inactive)
browser-plus, v0.0.98 (inactive)
busy-signal, v1.4.3 (active)
chary-tree-view, v0.2.3 (active)
default-encoding, v0.8.0 (active)
diff-pane, v0.3.0 (inactive)
docblockr, v0.11.0 (active)
flex-tool-bar, v0.12.0 (active)
format-actionscript, v0.2.0 (inactive)
format-sql, v0.3.0 (inactive)
hex, v0.6.2 (active)
highlight-selected, v0.11.2 (active)
html-entities, v0.4.0 (active)
html-head-snippets, v0.2.0 (active)
html-id-class-snippets, v1.4.1 (active)
html-include-resource, v1.3.0 (inactive)
html-outliner, v0.1.1 (active)
html-to-css, v0.2.2 (inactive)
intentions, v1.1.5 (active)
jsdoc-generator, v0.2.3 (active)
jsdoc-preview, v1.2.1 (active)
language-actionscript, v0.2.0 (active)
language-actionscript3, v0.3.0 (active)
language-api-blueprint, v1.0.2 (active)
language-confluence-wiki, v0.2.0 (active)
language-dots, v0.0.4 (active)
language-htaccess, v0.1.1 (active)
language-mediawiki, v2.2.0 (active)
language-pascal, v0.20.2 (active)
language-source-cfg, v0.3.1 (active)
language-sql-mysql, v0.3.1 (active)
language-twiki, v0.4.0 (active)
language-wp, v0.1.1 (active)
linter, v2.0.0 (active)
linter-flexpmd, v0.1.9 (active)
linter-raml, v1.0.1 (inactive)
linter-spell, v0.15.0 (inactive)
linter-spell-html, v0.7.0 (inactive)
linter-ui-default, v1.2.4 (active)
linter-xmllint, v1.4.3 (active)
markdown-pdf, v1.5.4 (inactive)
markdown-themeable-pdf, v1.2.0 (inactive)
minimap, v4.25.7 (active)
minimap-autohide, v0.10.1 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-cursorline, v0.2.0 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.6.1 (active)
open-no-binaries, v0.1.1 (active)
pane-browser, v1.6.0 (active)
prime-file-icons, v0.3.0 (active)
qolor, v0.4.2 (active)
raml, v0.2.0 (active)
remote-edit, v1.9.0 (active)
tool-bar, v1.1.0 (active)
tool-bar-almighty, v0.8.2 (active)
tool-bar-atom, v1.7.0 (inactive)
tool-bar-config, v0.1.0 (active)
tool-bar-main, v0.0.10 (inactive)
tool-bar-markdown-writer, v0.3.0 (active)
tool-bar-shortcuts, v0.1.5 (inactive)
tree-ignore, v0.6.2 (active)
tree-view-open-files, v0.3.0 (active)
untitled-no-more, v0.1.0 (active)
wordpress-api, v1.2.2 (active)
wordpress-dictionary, v4.4.0 (active)
xml-formatter, v0.11.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (active)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (active)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by azizur** [comment]
Hi @ajwsert,

Thanks for raising this issue.

Looking at the above information is does not appear to be related to the `wordpress-api` package.

**Comment by ajwsert** [comment]
No problem @azizur, however, huh, that's weird because that issue is raised when changing the file syntax to Wordpress, no other plugin or syntax does it. Maybe I forgot some info in that report? I just pasted what was copied by clicking Copy button in that error popup in Atom. By the way, selecting that as syntax seems to do nothing (nothing changes in syntax) beside raising that error.

**Comment by azizur** [comment]
The stack trace does not appear to indicate an issue with this plugins.

**Comment by ajwsert** [comment]
Hmm, I see. Alright, I'll try to see what could be triggering it, maybe it was just coincidence with this plugin.

**Comment by winstliu** [comment]
Hello @azizur!  This is definitely an issue with wordpress-api, even though the stack trace doesn't indicate so.  This error occurs when one of the language patterns has an invalid repeat quantifier.  For example, the very simple regex `?` would trigger this error.  Other examples might include `(?=a)*`, `\\b+`, etc.  Please check your regexes to make sure this isn't happening.
